### ISSUE TITLE
Proposal of logo and icon for the application

### ISSUE THREAD

**Issue by richardbmx** [adityakamble49/dcipher-app#1]
Hello I am a graphic designer and I make contributions to open source projects through the Utopian-io platform, (with them I earn the rewards if you use my proposal) I attach a proposal for your project of an icon and a logo if you like I can send you all the files for you to attach to your project. :-)

![presentacion para github](https://user-images.githubusercontent.com/35604837/39402529-92dfdc56-4b2f-11e8-9276-5b02d4c09701.png)

**Comment by adityakamble49** [comment]
Thanks for Proposal.
Icon looks good. But actually the original icon I designed is matches with app theme with those black and white colors. I think I will stick to old icon for now.
Anyway thanks for suggession. 

Will it be okay to ask you for icons for upcoming open source projects, so we can collaborate?

**Comment by richardbmx** [comment]
How good that you like the proposal can be modified if you wish and make it more consistent with your application ..

If yes you can write me to design for other future projects I would gladly make the contribution :-)

**Comment by adityakamble49** [comment]
Cool. Will let you know if I need logo for upcoming projects.
