### ISSUE TITLE
Alternative to Google Play

### ISSUE THREAD

**Issue by IzzySoft** [adityakamble49/dcipher-app#2]
I just found your repo – and see your app seems to be very privacy friendly: no trackers, not even the Internet permission required! Exactly what one should expect from an app like this, dealing with sensitive content (and unfortunately not found in many apps of this category).

So I wondered: why is this app only available via Playstore – so us "tin foils" avoiding that place for privacy reasons cannot install it? Would you be open to see your app in other places, like [F-Droid](https://f-droid.org/)? Expecting you would, I've opened a [request for packaging](https://gitlab.com/fdroid/rfp/issues/831) with F-Droid for your app.

Just in case you don't know F-Droid: Details can be found in my article on it, [F-Droid: The privacy-friendly alternative to Google Play Store](https://android.izzysoft.de/articles/named/fdroid-intro-1).

**Comment by IzzySoft** [comment]
PS: Our bot found a little issue with your gradle when scanning your repo – so regardless of whether you agree to have your app on F-Droid, you might wish to check (and fix) that. You can find it [here](https://gitlab.com/fdroid/rfp/issues/831#note_126901235).

**Comment by adityakamble49** [comment]
@IzzySoft Sure. I am open to publish that in F-Droid. In addition I am not using any Google Services for the app and its completely offline.
Let me know where to upload APK for the same

**Comment by adityakamble49** [comment]
> PS: Our bot found a little issue with your gradle when scanning your repo – so regardless of whether you agree to have your app on F-Droid, you might wish to check (and fix) that. You can find it [here](https://gitlab.com/fdroid/rfp/issues/831#note_126901235).

You mean  

> unverified gradle download?

I will update it and post update here

**Comment by adityakamble49** [comment]
@IzzySoft Gradle distributionSha256Sum added ca3dcf8
Checkout and Let me know

**Comment by adityakamble49** [comment]
> No need for that, as F-Droid builds apps from their resp. sources. If you want your app in my repo until it's picked up by the official one, you can attach the APK to its resp. release, then my updater can pick it up. I'd then keep it available there until it's officially listed (and then remove it from mine to avoid confusion).

Latest release apk is uploaded under GitHub Releases [1.0.1](https://github.com/adityakamble49/dcipher-app/releases/tag/1.0.1)

**Comment by IzzySoft** [comment]
Thanks a lot! Should show up [here](https://apt.izzysoft.de/fdroid/index/apk/com.adityakamble49.dcipher) in about 5 hours (next sync time).

**Comment by IzzySoft** [comment]
> Checkout and Let me know

Gradlew was [confirmed fixed](https://gitlab.com/fdroid/rfp/issues/831#note_127677970). The [merge request](https://gitlab.com/fdroid/fdroiddata/merge_requests/4152) to integrate your app with the official repo has been created. If nothing breaks, it could be finished before the year is over :wink: :clinking_glasses: Thanks for your support!

**Comment by adityakamble49** [comment]
Great. Thanks :smiley:

**Comment by adityakamble49** [comment]
Sure. Let's keep this open until it's available in official repo. I will close it after that.
Thanks again :+1:

**Comment by adityakamble49** [comment]
@IzzySoft Just checked on F-Droid, DCipher app is now available here [F-Droid DCipher](https://f-droid.org/en/packages/com.adityakamble49.dcipher/)

Will Close this issue now. 
Thanks

**Comment by IzzySoft** [comment]
Yes, indeed! Congrats! :tada:

**Comment by adityakamble49** [comment]
@IzzySoft I have updated app, but still not reflected on F-Droid? How to get it updated on F-Droid?

**Comment by IzzySoft** [comment]
Just have a little patience :innocent: The [Metadata file](https://gitlab.com/fdroid/fdroiddata/tree/master/metadata/com.adityakamble49.dcipher.yml) already reflects your update, so it should show up soon.

**Comment by adityakamble49** [comment]
@IzzySoft Okay. Thanks

**Comment by IzzySoft** [comment]
No problem. It's unfortunate it often takes that long. The main repo isn't a good place for "nightlies" obviously (that's what my repo is for, among others – guess why e.g. FairEmail is in both).

**Comment by adityakamble49** [comment]
Okay. Its take time, I thought it should update in 1-2 days. But its been 4 days since I have pushed new version.
Anyways, As its in metadata, it will update soon

**Comment by IzzySoft** [comment]
Right. Sometimes takes up to a week (especially if the build server has issues – which was the case a few days ago).
