### ISSUE TITLE
Copy text to clipboard via long press

### ISSUE THREAD

**Issue by WolfgangAxel** [adityakamble49/dcipher-app#3]
First off, this is a great app; simple, clean, and increasingly important in this day and age. My only suggestion for improvement would be to copy the encrypted or decrypted text by long-pressing the output text box, or simply making that text selectable for copying. I found myself doing that instinctively multiple times, and personally, I find opening the share menu just to copy text a little cumbersome since that menu has to repopulate every time it's opened.

**Comment by adityakamble49** [comment]
Glad you liked the app, and thanks for the suggestion, I will add this task for upcoming release.

**Comment by adityakamble49** [comment]
@WolfgangAxel Updated app to support Selectable Text after Encryption as well as Decryption.
Will be available soon on Play Store
